version: '3.4'

services:


  hospitalapi:
    networks:
      - database
    build:
      dockerfile: Stacks/Build/Hospital/Dockerfile
      context: ../
    ports:  
      - "8088:80"
    restart: on-failure
    depends_on:
      - database
    environment:
      HOSPITAL_DB_PATH: "host=database;port=5432;database=HOSPITAL;username=postgres;password=postgres"
    volumes:
      - type: volume
        source: web-sql
        target: /app/sql
      


  database:
    networks:
      - database
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "HOSPITAL"
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/postgresql/data
      - type: volume
        source: web-sql
        target: /docker-entrypoint-initdb.d/

    ports:
      - 5432:5432

volumes:
  database-data:
  web-sql:

networks:
  public:
    name: public
    driver: bridge
  application:
    name: application
    driver: bridge
  database:
    name: database
    driver: bridge
