version: '3.4'

secrets:
  postgres_password:
    external: true
  hospital_db_path:
    external: true
  integration_db_path:
    external: true
  pharmacy_db_path:
    external: true

services:

  gateway:
    image: nikolaaleksic/gateway
    build:
      context: ../
      dockerfile: Stacks/Build/Gateway/Dockerfile
      target: gateway
      args:
        - HOSPITAL_API_URL=hospitalapi:80
        - INTEGRATION_API_URL=integrationapi:80
    restart: on-failure
    ports: 
      - 8080:8080
    depends_on:
      - hospitalapi
      - pharmacyapi
      - integrationapi

  hospitalapi:
    image: nikolaaleksic/hospital
    volumes:
      - ./data:/data/
    entrypoint: ['/bin/bash', '-c' ,  '/data/wait-for-it.sh hospitaldb:5432 -t 60 && source /data/env_secrets_expand.sh && dotnet HospitalApi.dll']
    build:
      dockerfile: Stacks/Build/Hospital/Dockerfile
      context: ../
    ports:  
      - "8088:7000"
    restart: on-failure
    depends_on:
      - hospitaldb 
    secrets:
      - source: hospital_db_path
    environment:
      HOSPITAL_DB_PATH: DOCKER-SECRET->hospital_db_path

  pharmacyapi:
    image: nikolaaleksic/pharmacy
    volumes:
      - ./data:/data/
    entrypoint: ['/bin/bash', '-c' ,  '/data/wait-for-it.sh pharmacydb:5432 -t 60 && source /data/env_secrets_expand.sh && dotnet PharmacyApi.dll']
    build:
      dockerfile: Stacks/Build/Pharmacy/Dockerfile
      context: ../
    ports:  
      - "8089:7001"
    restart: on-failure
    depends_on:
      - pharmacydb
      - rabbitmq
    secrets:
      - source: pharmacy_db_path
    environment:
      RABBITMQ_HOST: "rabbitmq"
      PHARMACY_DB_PATH: DOCKER-SECRET->pharmacy_db_path

  integrationapi:
    image: nikolaaleksic/integration
    volumes:
      - ./data:/data/
    entrypoint: ['/bin/bash', '-c' ,  '/data/wait-for-it.sh integrationdb:5432 -t 60 && source /data/env_secrets_expand.sh && dotnet IntegrationApi.dll']
    build:
      dockerfile: Stacks/Build/Integration/Dockerfile
      context: ../
    ports:  
      - "8090:7002"
    restart: on-failure
    depends_on:
      - integrationdb
      - rabbitmq
    secrets:
      - source: integration_db_path
    environment:
      INTEGRATION_DB_PATH: DOCKER-SECRET->integration_db_path
      RABBITMQ_HOST: "rabbitmq"

  patient-ui:
    image: nikolaaleksic/patientui
    build:
      context: ../
      dockerfile: Stacks/Build/PatientUi/Dockerfile
    ports:
      - "8081:8081"
    container_name: patient-ui

  manager-ui:
    image: nikolaaleksic/managerui
    build:
      context: ../
      dockerfile: Stacks/Build/ManagerUi/Dockerfile
    ports:
      - "8082:8082"
    container_name: manager-ui

  integration-ui:
    image: nikolaaleksic/integrationui
    build:
      context: ../
      dockerfile: Stacks/Build/IntegrationUi/Dockerfile
    ports:
      - "8083:8083"
    container_name: integration-ui

  hospitaldb:
    image: postgres:13
    secrets:
      - postgres_password
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "HOSPITAL"
    ports:
      - 5454:5432

  pharmacydb:
    image: postgres:13
    secrets:
      - postgres_password
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "PHARMACY"
    ports:
      - 5455:5432

  integrationdb:
    image: postgres:13
    secrets:
      - postgres_password
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "INTEGRATION"
    ports:
      - 5456:5432

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
