name: Automated deploy to server

on:
  workflow_dispatch:
  push:
    branches: 
      - 'master'
      - 'feature/upload-to-server'

jobs:
  deploy:
    runs-on : ubuntu-latest
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          command_timeout: 200m
          host: ${{ secrets.SSH_HOST }}
          username: 'student'
          key: ${{ secrets.SSH_KEY }}
          port: 22207
          script: |
            cd psw/mainrepo
            docker system prune -f
            git checkout feature/upload-to-server
            git pull
            cd Stacks
            docker-compose build --no-cache
            docker-compose up -d


