name: Automated deployment of integration nuget

on:
  push:
    branches: [ nuget/integration ]
    tags: 
      - 'v*'

env:
  INTEGRATION-DLL-PATH : 'mainrepo/Integration/IntegrationClassLib/Integration.csproj'
  OUTPUT-DLL-DIR : '${{ github.workspace }}\output'
  NUGET-SOURCE-URL : 'https://api.nuget.org/v3/index.json'

jobs:
  deploy-nuget:
    runs-on : ubuntu-latest
    steps:
      - name : Pulling repository to the VM
        uses : actions/checkout@v2
      
      - name : Installing the dotnet tool
        uses: actions/setup-dotnet@v1
        with:
          dotnet-verison: '5.0.x'

      - name : Listing dir
        run : ls -a

      - name : Restore and build packages
        id : build-results
        run : dotnet build ${{ env.INTEGRATION-DLL-PATH }} --configuration Release

      - name : Determining the version
        id : version-step
        uses : battila7/get-version-action@v2

      - name : Packaging the dll
        run: dotnet pack ${{ env.INTEGRATION-DLL-PATH }} --no-restore --no-build --configuration Release  -p:PackageVersion=${{steps.version-step.outputs.version-without-v}} --output ${{ env.OUTPUT-DLL-DIR }}

      - name : Pushing to nuget repository
        run: dotnet nuget push ${{ env.OUTPUT-DLL-DIR }}/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s ${{ env.NUGET-SOURCE-URL }}
